Update https://buildingdata.energy.gov.
BuildingEnergyTools/tools-website pull request #79
Opened 2023-03-28 22:39 UTC by haneslinger

Sydney wants the video up.

2023-03-29 16:49 UTC, nllong commented
I'm fixing the s3 keys today. IT needs to get involved because of their security changes with SSO.

2023-03-29 23:31 UTC, nllong commented
> I'm fixing the s3 keys today. IT needs to get involved because of their security changes with SSO.

Okay, I fixed the deployment. A couple of things happened. 1) IT gave us a new AWS access key that doesn't expire after 6 hours, 2) I removed the old 'shallwefootball' action with a straight-up call to `aws cli`. 3) updated the checkout action to v3.

2023-03-29 23:31 UTC, nllong approved these changes

2023-03-30 15:40 UTC, axelstudios approved these changes

2023-03-30 19:25 UTC, nllong requested changes
Point to youtube version instead of the vimeo version.

https://www.youtube.com/watch?v=3-tVQZ996lU

2023-03-31 17:45 UTC, merged